# fly.toml app configuration file generated for autodelete-discord on 2023-05-07T22:13:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autodelete-discord"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yyz"
processes = []

[build]

[env]

[experimental]
  auto_rollback = true
