# fly.toml file generated for autodelete-discord on 2023-05-06T21:58:19-04:00

app = "autodelete-discord"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true
